### ISSUE TITLE
Please clarify license to enable contributions

### ISSUE THREAD

**Issue by gwpl** [DaveAppleton/EtherscanAPI#1]
Please add license to others can contribute.
How to do this you may try to create new test project on github and you have wizzard,
or follow examples:

* https://github.com/barcode-utils/empty-project-template-with-MIT_AKA_X11-License
* https://github.com/barcode-utils/empty-project-template-with-Apache-License2.0

Please consider more open (but still protecting creator) license for compatibility : https://en.wikipedia.org/wiki/File:Floss-license-slide-image.png

Thank you.

**Comment by DaveAppleton** [comment]
Apologies for taking so long....
Done.

**Comment by gwpl** [comment]
Thank you !
